### ISSUE TITLE
複数Headerの処理がおかしい

### ISSUE THREAD

**Issue by nilwurtz** [uzabase/playtest#16]
https://github.com/uzabase/playtest/blob/274626775ba7cd2aeee55656651e54c0c298ce05/playtest-gauge-rest/src/main/kotlin/com/uzabase/playtest/gauge/rest/http/HttpStep.kt#L131
```
    fun toHeaderMap(header: String): Headers {
        return header
            .split("\n")
            .map { line ->
                line.split(":", limit = 2)
                    .let {
                        it[0].trimStart() to it[1].trim()
                    }
            }
            .toTypedArray()
            .let(::headersFrom)
    }
```

split内の\nがエスケープされていないので、Splitがうまくできていない。

`ヘッダー"user-id: 100001 \n content-type: application/json"で ~~` とすると、後ろのヘッダーが送られていないよう。

**Comment by nilwurtz** [comment]
これはファイル読み込みを想定した処理かも。
改行コードを "\n"の文字に変換し、それをさらにSplitすれば両方に対応できるか。

**Comment by ayato-p** [comment]
@nilwurtz 
使っているライブラリのバージョンと、問題が起こるstepを教えてもらえますか？
以下のテストで挙動が担保されているように見えるんですが…
https://github.com/uzabase/playtest/blob/310421b1563e5f24db5ad0f164b8a6c77e547198/playtest-gauge-rest/specs/http/get.spec#L16-L20

**Comment by itsuki-yamada** [comment]
既存のPlayTest使っている箇所でも確認しても問題なさそうだったので一旦closeします
