### ISSUE TITLE
:sparkles:: URLにリクエストを送るステップでボディの指定にファイルパスを使うことができる

### ISSUE THREAD

**Issue by adwd** [uzabase/playtest#31]
### what?

- `URL<url>にボディ<jsonFilePath>JSONファイルの内容でPUTリクエストされた` というステップ
- ボディのJSONをファイルで書くことができる

### why?

`URL<url>にボディ<requestBody>、ヘッダー<header>で、PUTリクエストを送る` というステップは既存でありますが、ボディが大きくなると読みにくくなるのでファイルを指定できると便利だと思います。 `API<apiName>のURL<url>にボディ<jsonFilePath>JSONファイルの内容でPUTリクエストされた` という既存のステップのURL版みたいなイメージです。

**Comment by nilwurtz** [comment]
gaugeのFileパラメータでファイルパスを指定することができるので、この機能で十分な気がします
この場合はGaugeプロジェクトのルートからのパスになります
https://docs.gauge.org/writing-specifications.html?os=macos&language=javascript&ide=vscode#special-parameter-file-1

なので
`URL"xxx"にボディ<file:/path/to/file.json>、ヘッダー”xxxx"で、PUTリクエストを送る` で実現可能です

`URL<url>にボディ<jsonFilePath>JSONファイルの内容でPUTリクエストされた` ってStepがそもそも不要な気がしており、これがあることで混乱を生む感じがしますね・・・

**Comment by adwd** [comment]
すいません、既に機能があったのを知らなかったです。
そちらを使うようにします。
